"""empty message

Revision ID: 92f1da3d5c27
Revises: 2c45be1e42a4
Create Date: 2017-11-03 14:39:15.929363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f1da3d5c27'
down_revision = '2c45be1e42a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goodname', sa.String(), nullable=True),
    sa.Column('goodprice', sa.Float(), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    # ### end Alembic commands ###
